FROM nvidia/cuda:10.0-devel

RUN useradd -ms /bin/bash control

USER control
ADD requirements* /tmp/

RUN pip install --upgrade pip && \
    pip install --user -r /tmp/requirements.txt && \
    pip install --user -r /tmp/requirements_cpu.txt

